name: Clean Repository

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Delete unnecessary files
        run: |
          # 修正后的删除命令（双重保护 .git 目录）
          find . -mindepth 1 \
            -not -path './.github/*' \
            -not -path './.git/*' \
            -not -path './.git' \
            -not -name 'home.zip' \
            -exec rm -rf {} + || true

          echo "清理后验证 .git 是否存在："
          ls -al .git

      - name: Commit changes
        run: |
          # 确保在正确目录执行
          cd "$GITHUB_WORKSPACE" || exit 1
          
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # 强制重新加载 git 索引
          git reset --hard
          git clean -fd

          git add -A
          if [ -z "$(git status --porcelain)" ]; then
            echo "没有需要提交的更改"
          else
            git commit -m "清理仓库：仅保留 home.zip 和 .github"
            git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref }}
          fi
