name: Clean Repository

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Delete unnecessary files
        run: |
          # 修正后的 find 命令（移除换行符）
          find . -mindepth 1 \
            -not -path './.github/*' \
            -not -name 'home.zip' \
            -not -name '.git' \
            -exec rm -rf {} + || true

          # 验证结果
          echo "清理后文件结构："
          ls -al

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git add -A
          if [ -z "$(git status --porcelain)" ]; then
            echo "没有需要提交的更改"
          else
            git commit -m "清理仓库：仅保留 home.zip 和 .github"
            git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref }}
          fi
