name: Unzip File

on:
  workflow_dispatch: # 允许手动触发

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Unzip file
        run: |
          # 将 YOUR_FILE_NAME.zip 替换为你的实际 ZIP 文件名
          unzip -o home.zip -d .
          
          # 可选：显示解压后的目录结构
          ls -al
          
          # 在 unzip step 之后添加以下内容：
      - name: Commit extracted files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Add extracted files" || echo "No changes to commit"
          git push
